# Generated by Django 2.2.6 on 2019-12-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('sliderImgId', models.AutoField(primary_key=True, serialize=False)),
                ('sliderImg', models.ImageField(upload_to='Slider-Image')),
            ],
        ),
    ]
