# Generated by Django 2.2.6 on 2019-12-05 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ecommerce', '0002_sliderimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='userId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartId', models.AutoField(primary_key=True, serialize=False)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.Products')),
            ],
        ),
    ]
