# Generated by Django 2.2.6 on 2019-12-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0006_cart_productquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productRatings',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='products',
            name='productSales',
            field=models.IntegerField(default=0),
        ),
    ]
