# Generated by Django 2.2.6 on 2019-12-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0009_delivery_deliverystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='sliderTeaser',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='sliderTitle',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
