# Generated by Django 2.2.6 on 2019-12-16 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ecommerce', '0011_auto_20191216_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('deliveryId', models.AutoField(primary_key=True, serialize=False)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.Products')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.DeliveryStatus')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
