# Generated by Django 2.2.6 on 2019-12-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce', '0012_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderQuantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
