# Generated by Django 2.2.6 on 2019-12-17 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ecommerce', '0014_products_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('commentText', models.TextField()),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecommerce.Products')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
